### ISSUE TITLE
ubuntu error

### ISSUE THREAD

**Issue by dcrystalj** [rgl/mail-vagrant#1]
i get this error on vagrant up
```
Couldn't open file /home/xyz/git/mail-vagrant/ubuntu-16.04-amd64
```

**Comment by rgl** [comment]
Oh, I forgot to mention on the README that you first need to create the base box with https://github.com/rgl/ubuntu-vagrant

**Comment by rgl** [comment]
Add the note to the README file in https://github.com/rgl/mail-vagrant/commit/885bf8f7978300ffba9db1718a775b28be76c604
